### ISSUE TITLE
Support configuring Validators 

### ISSUE THREAD

**Issue by cloudronin** [wisecubeai/pythia#8]
We need a way to configure Pythia to only run one or more configured/enabled validators as part of its processing. Right now its not clear if it runs all of the validators all the time or not.

**Comment by pratacosmin** [comment]
### Validators
Pythia Offers a variety of LLM validators in order to check the input and output for the model.
This validators can be enabled or disabled using the config file `configurations/validators/config.yaml`.

```yaml
    - name: detect_pii
      description: "The Anonymize Scanner acts as your digital guardian, ensuring your user prompts remain confidential and free from sensitive data exposure."
      source: llm Guard
      enabled: true
      input: input_reference
      output: input_response
```


The response for the validators Will pe set on the pythia Traces.

![img.png](img.png)
